---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ovaimporter
  name: ovaimporter
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app: ovaimporter
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ovaimporter
  name: ovaimporter
spec:
  containers:
  - args:
    - reflex
    - run
    - --frontend-only
    envFrom:
    - configMapRef:
          name: ovaimporter-params 
    # env:
    # - name: API_URL
    #   value: http://192.168.68.67:8000
    image: quay.io/brochwer/ovaimporter:latest
    name: ovaimporter-fe
    ports:
    - containerPort: 3000
    securityContext: {}
  #   stdin: true
  #   tty: true
  #   volumeMounts:
  #   - mountPath: /tmp/ovas
  #     name: tmp-ovas-host-0
  # volumes:
  # - hostPath:
  #     path: /tmp/ovas
  #     type: Directory
  #   name: tmp-ovas-host-0

