---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ovaimporter-be
  name: ovaimporter-be
  namespace: ova-import-demo
spec:
  host: ovaimporter-be-ova-import-demo.apps.cnv2.engineering.redhat.com
  port:
    targetPort: 8000
  to:
    kind: Service
    name: ovaimporter-be
    weight: 100
  wildcardPolicy: None

--- 
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ovaimporter
  name: ovaimporter
  namespace: ova-import-demo
spec:
  host: ovaimporter-ova-import-demo.apps.cnv2.engineering.redhat.com
  port:
    targetPort: 3000
  # tls:
  #   termination: edge
  to:
    kind: Service
    name: ovaimporter
    weight: 100
  wildcardPolicy: None